// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vayqiddmxtkqtfdzdqal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZheXFpZGRteHRrcXRmZHpkcWFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNzY0OTksImV4cCI6MjA2Nzg1MjQ5OX0.URqYvdKOj-TVMsBwOQbdXPjVZKnruf20w9nJJLvZCbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});